In [45]:
#We import the libraries
import pandas as pd
import matplotlib as mtp
import numpy as np
#We import the library who's going to make the prediction
from sklearn import tree

In [44]:

data = pd.read_csv('TallasContinentes.csv')
data = data.rename(columns={
    'C':'Continent',
    'Sexo': 'Gender',
    'Altura': 'Height',
    'Peso': 'Weight',
    'IMC': 'BMI'
                           })
data

         Continent Gender  Height  Weight   BMI
0           Europa      M    1.80    87.1  87.1
1           Europa      M    1.80    86.4  86.4
2           Europa      F    1.67    71.0  71.0
3   Asia y oceania      M    1.79    88.9  88.9
4          America      F    1.55    68.1  68.1
5           Africa      F    1.58    58.0  58.0
6           Europa      M    1.78    86.9  86.9
7           Europa      M    1.77    83.0  83.0
8          America      M    1.72    77.3  77.3
9           Africa      M    1.67    60.2  60.2
10          Africa      F    1.58    71.6  71.6
11          Europa      F    1.64    72.9  72.9
12  Asia y oceania      F    1.64    86.6  86.6
13         America      M    1.77    90.4  90.4
14          Africa      M    1.70    74.9  74.9
15          Europa      F    1.66    69.3  69.3
16         America      M    1.71    77.8  77.8
17          Africa      M    1.69    62.9  62.9
18          Africa      F    1.59    60.3  60.3
19          Europa      F    1.65    72.3  72.3
20  Asia y oceania      M    1.71    76.7  76.7
21          Europa      M    1.77    84.2  84.2
22  Asia y oceania      M    1.65    60.3  60.3
23         America      M    1.68    76.3  76.3
24          Africa      M    1.68    70.3  70.3
25          Europa      F    1.64    68.0  68.0
26  Asia y oceania      F    1.57    64.2  64.2
27         America      F    1.59    67.3  67.3
28          Africa      M    1.68    64.0  64.0
29  Asia y oceania      M    1.71    70.5  70.5
30  Asia y oceania      M    1.71    79.4  79.4
31  Asia y oceania      F    1.59    68.5  68.5
32  Asia y oceania      M    1.68    82.2  82.2
33  Asia y oceania      F    1.59    71.7  71.7
34  Asia y oceania      F    1.53    52.4  52.4
35  Asia y oceania      M    1.76    94.0  94.0
36  Asia y oceania      F    1.56    76.1  76.1
37         America      F    1.58    67.7  67.7
38          Africa      F    1.56    55.9  55.9
39  Asia y oceania      F    1.65    73.5  73.5
40         America      F    1.64    77.4  77.4
41          Africa      F    1.59    73.7  73.7
42  Asia y oceania      M    1.65    69.5  69.5
43  Asia y oceania      F    1.59    59.1  59.1

In [46]:
data.describe()

          Height     Weight        BMI
count  44.000000  44.000000  44.000000
mean    1.661818  72.927273  72.927273
std     0.075059   9.956495   9.956495
min     1.530000  52.400000  52.400000
25%     1.590000  67.600000  67.600000
50%     1.655000  72.000000  72.000000
75%     1.710000  78.200000  78.200000
max     1.800000  94.000000  94.000000

In [101]:
clf = tree.DecisionTreeClassifier()
#continent = np.asarray(data[["Continent"]])


#x = np.array([data.Height, data.Weight, data.BMI])
gender = data.Gender

new_data = data[['Height','Weight','BMI']]
new_data = new_data.values

clf = clf.fit(new_data,gender)

In [102]:
height = input("height:")
weight = input("weight:")
bmi = weight/height**2
prediction = clf.predict([[height,weight,bmi]])
print "It's very probable the person is "prediction

height:1.65
weight:68
['M']